services:
  hbbs:
    container_name: renasis-hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r remote.renace.tech:21117 -k _
    volumes:
      - ./data:/root
    network_mode: "host"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: renasis-hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped

  renasis-api:
    container_name: renasis-api-server
    image: ghcr.io/kingmo888/rustdesk-api-server:latest
    restart: unless-stopped
    ports:
      - "21114:21114"
    environment:
      - CSRF_TRUSTED_ORIGINS=http://remote.renace.tech:21114,https://remote.renace.tech
      - ID_SERVER=remote.renace.tech
    volumes:
      - ./api_data:/rustdesk-api-server/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
