services:
  jarvix:
    image: jarvix:latest
    build: .
    volumes:
      - ./data:/root/.openclaw
    networks:
      - RenaceNet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jarvix.rule=Host(`renace.tech`) && PathPrefix(`/jarvix`)"
        - "traefik.http.routers.jarvix.entrypoints=websecure"
        - "traefik.http.routers.jarvix.tls=true"
        - "traefik.http.routers.jarvix.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.jarvix.priority=3000"
        - "traefik.http.services.jarvix.loadbalancer.server.port=18789"
        - "traefik.http.routers.jarvix.middlewares=jarvix-stripprefix"
        # - "traefik.http.routers.jarvix.middlewares=jarvix-stripprefix,jarvix-auth"
        # - "traefik.http.middlewares.jarvix-auth.basicauth.users=renace:$$apr1$$XQZ.B0..$$V4Zq9c9RzXU7q9qW7q9qW/"
        - "traefik.http.middlewares.jarvix-stripprefix.stripprefix.prefixes=/jarvix"
        - "traefik.docker.network=RenaceNet"

networks:
  RenaceNet:
    external: true
