#!/usr/bin/env bash
# ==============================================================================
# Genera secretos criptográficamente fuertes si faltan o son placeholders.
# Los escribe en .env (estable entre deploys) sin tocar SMTP/Odoo/DB existentes.
# Uso: ./scripts/ensure-secrets.sh
# ==============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/.env}"
EXAMPLE="$ROOT/.env.example"

gen() {
  # 32 bytes → base64url (~43 chars)
  openssl rand -base64 48 | tr -d '\n/+=' | head -c 48
  echo
}

is_placeholder() {
  local v="${1:-}"
  [ -z "$v" ] && return 0
  [ "${#v}" -lt 12 ] && return 0
  echo "$v" | grep -Eiq '^(change[_-]?me|your[-_]|tu[_-]|random-string|example|xxx+|TODO|FIXME|replace|changethis)' && return 0
  return 1
}

env_get() {
  local key="$1"
  [ -f "$ENV_FILE" ] || { echo ""; return; }
  # shell-safe read of KEY=value (supports quotes)
  python3 - "$ENV_FILE" "$key" <<'PY'
import sys
from pathlib import Path
path, key = sys.argv[1], sys.argv[2]
text = Path(path).read_text(encoding="utf-8", errors="replace")
for line in text.splitlines():
    s = line.strip()
    if not s or s.startswith("#") or "=" not in s:
        continue
    k, _, v = s.partition("=")
    if k.strip() != key:
        continue
    v = v.strip()
    if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
        v = v[1:-1]
    print(v)
    break
PY
}

env_set() {
  local key="$1"
  local val="$2"
  python3 - "$ENV_FILE" "$key" "$val" <<'PY'
import sys
from pathlib import Path
path, key, val = Path(sys.argv[1]), sys.argv[2], sys.argv[3]
if not path.exists():
    path.write_text("", encoding="utf-8")
lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
out = []
found = False
# Prefer double-quoted values; escape embedded quotes/backslashes/newlines
safe = val.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
new_line = f'{key}="{safe}"'
for line in lines:
    s = line.strip()
    if s and not s.startswith("#") and "=" in s and s.split("=", 1)[0].strip() == key:
        out.append(new_line)
        found = True
    else:
        out.append(line)
if not found:
    if out and out[-1].strip() != "":
        out.append("")
    out.append("# Auto-generated by scripts/ensure-secrets.sh")
    out.append(new_line)
path.write_text("\n".join(out) + "\n", encoding="utf-8")
PY
}

if [ ! -f "$ENV_FILE" ]; then
  if [ -f "$EXAMPLE" ]; then
    echo "→ Creando .env desde .env.example..."
    cp "$EXAMPLE" "$ENV_FILE"
  else
    touch "$ENV_FILE"
  fi
fi

KEYS=(
  ADMIN_TOKEN
  ADMIN_ACCESS_PASSWORD
  ADMIN_SESSION_SECRET
  PARTICIPANT_SESSION_SECRET
  PORTAL_ENCRYPTION_KEY
  NOTIFY_API_KEY
)

echo "🔐 Asegurando secretos en $ENV_FILE ..."
GENERATED=()
for key in "${KEYS[@]}"; do
  current="$(env_get "$key" || true)"
  if is_placeholder "$current"; then
    value="$(gen)"
    env_set "$key" "$value"
    GENERATED+=("$key")
    echo "   ✓ $key (nuevo)"
  else
    echo "   · $key (ya existía — no se regenera)"
  fi
done

chmod 600 "$ENV_FILE" 2>/dev/null || true

if [ "${#GENERATED[@]}" -gt 0 ]; then
  echo ""
  echo "✅ Secretos generados: ${GENERATED[*]}"
  echo "   Persistidos en .env (no se muestran aquí)."
  echo "   Para ver el PIN de admin (solo en el servidor):"
  echo "     grep '^ADMIN_ACCESS_PASSWORD=' $ENV_FILE"
else
  echo "✅ Todos los secretos de seguridad ya estaban definidos."
fi
